apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-sepapp
spec:
  acme:
    email: acile067@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-sepapp
    solvers:
      - http01:
          ingress:
            class: nginx
