apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-service
  template:
    metadata:
      labels:
        app: qr-service
    spec:
      containers:
        - name: qr-service
          image: ${ACR_NAME}.azurecr.io/qr-service:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /q/test/ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /q/test/ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: qr-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: qr-service
  ports:
    - name: qr-service
      port: 80
      targetPort: 8080
